name: Deploy docs

on:
  push:
    branches:
      - master
 
jobs:
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Update Aptitude
        run: |
          sudo apt-get update -y

      - name: Install Python3
        run: |
          sudo apt-get install -y python3 python3-pip

      - name: Build
        run: |
          bazel build //modpack

      - uses: actions/upload-artifact@v2
        with:
          name: corepack_waterfall.zip
          path: ./bazel-bin/modpack/corepack.zip